### ISSUE TITLE
feat: API Documentation

### ISSUE THREAD

**Issue by KimDoubleB** [mash-up-kr/piikii_Spring#10]
### 기능 설명

API 문서화를 코드로 구현 및 지원합니다.
- Springdoc을 이용하여 OpenAPI 스펙에 맞는 API 문서/Swagger를 생성합니다.
- 기존 비즈니스 코드에 영향을 줄이기 위해 interface 형태로 문서를 위한 코드를 별개로 작성합니다.
- 추후 필요에 따라 OAS 자동화 툴을 도입해 Client/Server 간의 API Schema를 공유합니다 (Design First)

**Comment by K-Diger** [comment]
https://github.com/Hejow/easy-restdocs-generator

지인이 REST DOCS 방식으로 문서를 만들고 Swagger UI로 API 문서를 만들어주는 라이브러리를 만들고있는데

요거 나중에 함 구경해보시죠
