### ISSUE TITLE
fix: 장소 등록/조회 시 스케줄 다중 저장

### ISSUE THREAD

**Issue by thguss** [mash-up-kr/piikii_Spring#158]
### 기능 설명

- 장소 하나 당 스케줄 id를 여러 개 저장할 수 있습니다.
- 장소 등록 시 썸네일 이미지처럼 , 포함 문자열 저장
- 장소 조회 시 스케줄 id 여러 개 조회

**Comment by K-Diger** [comment]
출격준비
