### ISSUE TITLE
bug: LEMON 좌표 오류

### ISSUE THREAD

**Issue by KimDoubleB** [mash-up-kr/piikii_Spring#194]
### 문제 상황

LEMON 위도/경도 좌표 값이 이상합니다.

### 기대하는 동작

LEMON 위도/경도 좌표 값을 알맞은 값으로 수정 필요합니다.
코스 생성 시 올바른 계산이 나와야 합니다.

**Comment by thguss** [comment]
활용 예정 openApi

https://developers.kakao.com/docs/latest/ko/local/dev-guide
