### ISSUE TITLE
chore: library version을 외부 파일로 관리

### ISSUE THREAD

**Issue by KimDoubleB** [mash-up-kr/piikii_Spring#22]
### 기능 설명

Library 버전을 외부 파일(ex. lib.version.toml 등)으로 관리합니다.

**Comment by K-Diger** [comment]
출격대기 (기존 buildSrc에서 좀 더 개선하기)

**Comment by KimDoubleB** [comment]
assign 뺏겼...!!!
근데 아주 굳 해보고 싶었지만 할 시간이 없었다.... 다음에 보고 배우겠슈
