### ISSUE TITLE
feat: Response format 구현

### ISSUE THREAD

**Issue by KimDoubleB** [mash-up-kr/piikii_Spring#8]
### 기능 설명

Error response format을 구현합니다.
- 응답 타입을 유연하게 활용할 수 있도록 제네릭 데이터 필드를 가질 수 있도록 구현합니다.
- 응답 타입 별 에러코드를 추가해 트러블 슈팅을 용이하게 합니다.
- 에러 응답을 핸들링 하는 핸들러를 구현하고, 에러 코드에 맞는 Status를 반환할 수 있도록 구현합니다.

**Comment by KimDoubleB** [comment]
### 기능 설명

Success Response format을 구현합니다.
- 응답 타입을 유연하게 활용할 수 있도록 제네릭 데이터 필드를 가질 수 있도록 구현합니다.

### 추가 정보

_No response_

**Comment by K-Diger** [comment]
Diger 출격 대기 중
