### ISSUE TITLE
feat: 코스 내 카테고리 목록 등록/수정

### ISSUE THREAD

**Issue by thguss** [mash-up-kr/piikii_Spring#87]
### 기능 설명

- 코스 내 카테고리 목록 등록 기능 (POST/PUT)

### 요청 처리 흐름

<img width="1325" alt="image" src="https://github.com/user-attachments/assets/abbd2eb2-0d02-456f-960c-23ecbbe2e62f">

<br/>

### 참고 디자인 뷰

<img width="300" alt="image" src="https://github.com/user-attachments/assets/6b313603-4d03-454f-93b6-30b8de99bab6" />

**Comment by yihyun-kim1** [comment]
꺄핫 잘 부탁드립니다 💗💗
